import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  return (
    <div className="h-screen w-screen flex justify-center items-center flex-col-reverse md:flex-row transition-all">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* LHS */}
      <div className="bg-black p-3 h-full w-full flex flex-col space-y-20 justify-center items-center  md:w-1/2 md:h-full  ">
        <div className="space-y-5 z-20">
          <p className="text-3xl font-bold text-white md:text-4xl">
            Front-end <span className="text-blue-600">Web & App</span> Developer
          </p>
          <p className="text-1xl font-bold text-white md:text-xl">
            I code beautifully responsive websites, and I{" "}
            <span className="text-red-600">love</span> what I do.
          </p>
        </div>

        <div className="w-full flex justify-around relative z-20">
          <Link href={"/Contact"}>
            <button className=" text-white bg-gray-700 p-5 rounded-3xl transition-all active:scale-75 hover:bg-gray-800">
              Say hello 👋
            </button>
          </Link>

          <Link href={"/About"}>
            <button className="text-white bg-gray-700 p-5 rounded-3xl transition-all active:scale-75 hover:bg-gray-800">
              About 👀
            </button>
          </Link>
        </div>
        {/* <div className="w-full h-auto absolute bottom-0 left-0 ">
          <Image src={"/footer.svg"} height="600px" width="600px" />
        </div> */}
      </div>

      {/* RHS */}
      <div className="h-1/2 w-full md:w-1/2 md:h-full bg-black flex justify-center items-center">
        <Image
          src="/Akshay.jpg"
          height={"600px"}
          width={"600px"}
          className="rounded-full"
        />
      </div>
    </div>
  );
}
